### ISSUE TITLE
Keep getting "Undefined" on [text]= property.

### ISSUE THREAD

**Issue by ADjenkov** [NathanWalker/nativescript-ng2-fonticon#19]
Using Android. Followed all the instruction. 
When I use `[text]="'fa-music' | fonticon:'fontawesome'"` on a `<Button>` e get `Undefined` as text.
When I use the same over a `<Label>` the entire label is not displayed.

Using {N} 2.4.2 + Ag2

PS: Also tried to manually download .ttf files in to `app/fonts/` along with `font-awesome.css` in `app/`

**Comment by pette9** [comment]
I'm getting this too, any solution?

**Comment by pette9** [comment]
it worked for me when i used `[text]="'fa-music' | fonticon"` instead of `[text]="'fa-music' | fonticon:'fontawesome' "`

**Comment by ADjenkov** [comment]
Thanks @pette9  it really works!
