### ISSUE TITLE
Request: accept .scss file in config

### ISSUE THREAD

**Issue by denkan** [NathanWalker/nativescript-ng2-fonticon#34]
I'm using .scss files in my code base, meaning I'm also .gitignore all generated .css files. This makes it troublesome to have a font-awesome.css file. 

Tried to rename to .scss but TNSFontIconModule.forRoot() config won't accept it. 

Perhaps it could?

**Comment by EddyVerbruggen** [comment]
But if the fontawesome css file actually css them it’s a waste or resources to have the Sass compiler parse that (probably) large file.

Can you not just make an execption in your .gitignore? “!path/to/font-awesome.css” should do it.

**Comment by denkan** [comment]
The fontawesome.scss itself shouldn't be compiled because it's not imported into any actually used file. Or am I missing something - does all .scss files get somewhat compiled? 

But good tip about exception - fair enough :)
