### ISSUE TITLE
Angular 5 removed OpaqueToken

### ISSUE THREAD

**Issue by netwobble** [NathanWalker/nativescript-ng2-fonticon#35]
core: OpaqueToken has been removed as it was deprecated since v4. Use InjectionToken instead.

https://github.com/angular/angular/blob/master/CHANGELOG.md#code-refactoring .

**Comment by hdrdiab** [comment]
After upgrading to angular 5 i am getting a run time error caused by ngx-fonticon ,i think this issue is related.

**Comment by Burgov** [comment]
this was fixed in c7711c2326d70d680feb929e2b8d2777d74edf31, so upgrade and you should be good
