### ISSUE TITLE
Can't find provide module

### ISSUE THREAD

**Issue by tomylee001001** [NathanWalker/nativescript-ng2-fonticon#5]
Hi ,

I  did every step you mention to implement this plugin in my app but i can find the provide module you use in the nativeScriptBootstrap.

**Comment by roblav96** [comment]
import it from @angular/core like so:

``` typescript
import {provide} from "@angular/core"

provide(TNSFontIconService, {
    useFactory: () => {
        return new TNSFontIconService({
            'icon': 'css/ionicons-android.css'
        }, true)
    }
})
```

**Comment by tomylee001001** [comment]
thanks.

**Comment by dondragon2** [comment]
How does this plugin now work with the final release of angular 2? where `provide` is not found in `@angular/core` anymore?

**Comment by roblav96** [comment]
@dondragon2 Add it to your `providers` in your `ngModule` like so:

``` typescript
providers: [
  { provide: TNSFontIconService,     useFactory: () => {
        return new TNSFontIconService({
            'icon': 'css/ionicons-android.css'
        }, true)
    } }
]
```

https://angular.io/docs/ts/latest/guide/dependency-injection.html#!#factory-provider
