### ISSUE TITLE
"pipes does not exist in type 'Component'"

### ISSUE THREAD

**Issue by odubuc** [NathanWalker/nativescript-ng2-fonticon#6]
Node: 4.5.0
Npm: 3.10.6
nativescript-angular: "0.6.0"
tns-core-modules: "2.2.1"
nativescript-ng2-fonticon: "^1.2.6"
typescript: 1.8.10

In your exemple:
@Component({
  selector: 'demo',
  template: '<Label class="fa" [text]="'fa-bluetooth' | fonticon"></Label> ',
  pipes: [TNSFontIconPipe]
})

I'm getting the following error:
"pipes does not exist in type 'Component'"

**Comment by chiefmc** [comment]
That's probably because you're on Angular 2.0.0 RTM

You need to put the pipe declaration into your app.module.ts like this:

``` typescript
    declarations: [
        AppComponent,
        EventListPage,
        TNSFontIconPipe,
    ]
```

**Comment by NathanWalker** [comment]
^ @chiefmc is correct. I will try to update the readme soon for Angular 2 final.

**Comment by odubuc** [comment]
Correct, I am on Angular 2.0. I'll wait for the updated readme. 
Thank you you for the help! :)

**Comment by dondragon2** [comment]
Similarly, the `provide` function is not available in `@angular/core`

**Comment by dondragon2** [comment]
Thanks that worked, however, I am getting `the pipe font icon not found` when I have the following declaration in the AppModule. 
`declarations: [
    AppComponent,
    TNSFontIconPipe,
  ]`
It works if I put it on the lower module declaration but then that causes another issue if I want to use it in more than 1 modules. I gives an error that the pipe is declared in more than places and i need to put it on a higher module like above.

**Comment by dondragon2** [comment]
Fortunately, I was able to fix it using a shared module.

```
import { NgModule, ModuleWithProviders } from "@angular/core";
import { TNSFontIconService, TNSFontIconPipe } from 'nativescript-ng2-fonticon';

@NgModule({
    declarations: [TNSFontIconPipe],
    exports: [TNSFontIconPipe]
})
export class SharedModule {
    static forRoot(): ModuleWithProviders {
        return {
            ngModule: SharedModule,
            providers: [{
                provide: TNSFontIconService,
                useFactory: () => {
                    return new TNSFontIconService({
                        'fa': 'font-awesome.css'
                    })
                }
            }]
        };
    }
}
```

app.module.ts

```
imports:[
    ...
   SharedModule.forRoot()
]
```

then in other modules that need it
`imports:[ ..., SharedModule]`

Don't know if there is a better way or if this is the correct way but this works for me

**Comment by 1moere1** [comment]
Just put it in declarations of app.module.ts. It is then available. According to Angular2 docs there isn't a pipes property for component: https://angular.io/docs/ts/latest/api/core/index/Component-decorator.html#!#stq=pipes&stp=1

At least it worked for me

**Comment by NathanWalker** [comment]
Please try `1.3.2` just published now if you are still having trouble. Note new usage guide for `TNSFontIconModule` in readme, for example in your `NgModule`:

```
imports: [
  NativeScriptModule,
  TNSFontIconModule.forRoot({
    'fa': 'font-awesome.css'
  })
]
```

**Comment by odubuc** [comment]
I finally got some time to give it a try. Thanks for the update it works perfectly!

**Comment by MaruthiEranki** [comment]
I got this issue. I mentioned custom pipe in declarations of app.module.ts. I also mentioned in the @component decorator. Some thing like this:
`@component({
  selector: '...',
  templateUrl: '...',
  styleUrls: '...',
  pipes: [myCustomPipe]
})`

So, everything worked fine after removing the pipes attribute from @component decorator.
